import type { Metadata } from 'next'
import { Urbanist } from "next/font/google";
import './globals.css'
import '@mantine/core/styles.css';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import localFont from 'next/font/local'


const PetitCochon = localFont({
  src: [{path:'../public/fonts/Petit Cochon.otf'},{path:'../public/fonts/Petit Cochon.ttf'}],
  display: 'swap', variable: '--font-PetitCochon',
})
const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return ( <html lang="en">
  <head>
    <ColorSchemeScript />
  </head>
      <body className={`${urbanist.className} ${PetitCochon.variable} text-black`}>
      <MantineProvider>{children}</MantineProvider>

      </body>
    </html>
  )
}
